Markup Sign_in ＆ Sign_up
SHOTA1107/freemarket_sample_48a pull request #20
Opened 2019-04-14 07:21 UTC by isoppu1632

#WHAT
・Sign_upの「登録方法選択」、「会員情報入力」、「電話番号承認」、「お届け先住所入力」、「支払方法」、「完了」のマークアップ
・Sign_inのログイン画面
・選択プルの項目ファイル

#WHY
・ユーザー登録の為

2019-04-14 07:28 UTC, yuki-uchida requested changes
CSSは全体的に見直してください

2019-04-14 07:28 UTC, yuki-uchida commented on app/assets/stylesheets/_test_user.scss
> +.progress-status{
BEMに従って、親要素の名前を継承したクラス命名をしてください

2019-04-14 07:28 UTC, yuki-uchida commented on app/assets/stylesheets/_test_user.scss
> +.birthday {
BEMを用いたCSSでは、様々な場所で使われるCSSはクラスを複数付与するのではなく、mixinで呼び出す形で記述します。

2019-04-14 07:28 UTC, yuki-uchida commented on app/views/devise/registrations/select/_prefecture_id.haml
> +      %option{:value => "1"} 北海道
active_hashを使ってください

2019-04-14 10:27 UTC, hiroki5123 commented
変更差分が大きすぎるので次からもう少し小さい単位でプルリクエストを作ってください。

2019-04-14 10:28 UTC, hiroki5123 commented
また、ビューファイルを作った時はこちらに画面のキャプチャを添付してください。

2019-04-14 10:29 UTC, ghost requested changes
現時点で使う予定のないファイルは削除して下さい

2019-04-14 10:29 UTC, hiroki5123 commented on app/views/layouts/application.html.haml
> +    %link{:href => "https://use.fontawesome.com/releases/v5.6.3/css/all.css", :rel => "stylesheet"}/
ハッシュロケット使わないようにしましょう

2019-04-14 10:29 UTC, hiroki5123 commented on app/views/layouts/application.html.haml
> +    %link{:href => "https://use.fontawesome.com/releases/v5.6.3/css/all.css", :rel => "stylesheet"}/
font-awesomeのgem入れているみたいなので、こちら削除してください。

2019-04-14 10:31 UTC, ghost requested changes
同じような記述が多いので、共通化できるところは部分テンプレートを使用してください

2019-04-14 12:03 UTC, isoppu1632 commented
![screencapture-localhost-3000-users-sign_in-2019-04-14-20_56_26](https://user-images.githubusercontent.com/48373985/56092574-c3b79700-5ef8-11e9-9dc9-9f7e02e6e467.png)
![screencapture-localhost-3000-users-sign_up-2019-04-14-20_49_57](https://user-images.githubusercontent.com/48373985/56092575-c3b79700-5ef8-11e9-8374-335189a16dfe.png)
![screencapture-localhost-3000-users-sign_up-2019-04-14-20_51_14](https://user-images.githubusercontent.com/48373985/56092576-c3b79700-5ef8-11e9-8ef4-02732f569c67.png)
![screencapture-localhost-3000-users-sign_up-2019-04-14-20_51_45](https://user-images.githubusercontent.com/48373985/56092577-c3b79700-5ef8-11e9-947f-f16ea5e83273.png)
![screencapture-localhost-3000-users-sign_up-2019-04-14-20_52_06](https://user-images.githubusercontent.com/48373985/56092578-c4502d80-5ef8-11e9-9255-91570d9713c6.png)
![screencapture-localhost-3000-users-sign_up-2019-04-14-20_52_31](https://user-images.githubusercontent.com/48373985/56092579-c4502d80-5ef8-11e9-8414-6d449d96c78d.png)
![screencapture-localhost-3000-users-sign_up-2019-04-14-20_55_22](https://user-images.githubusercontent.com/48373985/56092580-c4502d80-5ef8-11e9-96a3-3844680f827d.png)

2019-04-14 12:11 UTC, ghost requested changes

2019-04-14 12:11 UTC, hiroki5123 commented on app/assets/stylesheets/application.scss
> +// @import "./items";
使っていないのであれば削除しましょう

2019-04-14 12:11 UTC, hiroki5123 commented
指摘された部分に関して修正を行わない理由を教えてください。

2019-04-14 12:25 UTC, isoppu1632 commented on app/assets/stylesheets/application.scss
> +// @import "./items";
トップページを担当していた方のCSS部分です。
自分の作っている所に干渉して崩れてしまっている所があったので
一時的にコメントアウトにしています。
担当者が直し次第戻す予定です。

2019-04-14 12:28 UTC, ghost requested changes

2019-04-14 12:28 UTC, hiroki5123 commented on app/views/devise/confirmations/new.html.haml
> +%h2 Resend confirmation instructions
こちらは現時点で使う予定があるファイルですか？
もしないのであれば削除しましょう。
他のファイルも現時点で使う予定のないファイルが変更差分に入っていれば削除してください。

2019-04-14 12:28 UTC, hiroki5123 commented on app/assets/stylesheets/application.scss
> +// @import "./items";
承知しました。

2019-04-15 03:17 UTC, isoppu1632 commented on app/views/devise/confirmations/new.html.haml
> +%h2 Resend confirmation instructions
余分なDeviseのviewファイルを削除しました。

2019-04-15 03:28 UTC, miyagit reviewed
ハッシュロケットを使ってるところが蹴っこうあるので見直しましょう。

2019-04-15 03:28 UTC, miyagit commented on app/views/devise/registrations/_new_credit.haml
> +                %option{:value => ""} --
ハッシュロケットを直しましょう。

2019-04-15 03:42 UTC, isoppu1632 commented on app/views/devise/registrations/_new_credit.haml
> +                %option{:value => ""} --
修正いたしました。

2019-04-15 03:54 UTC, kuroko918 commented
いいかと思います！
LGTMです！

2019-04-15 04:12 UTC, merged